name: HyperStamina
author: PowerKG
version: experiment_v1.0
main: project.kg.STAMINA
commands:
   PP:
       description: mainly Commands.
       usage: /<command> <action>
permissions:
   HyperStamina.admin:
      description: Admin permission that can use admin cmd.